seaslog doesn't support PHP 8.4 anymore
Error: implicit declaration of function 'php_mkdir_ex'

From https://github.com/php/php-src/blob/php-8.4.0RC1/UPGRADING.INTERNALS:
  The php_mkdir() and php_mkdir_ex() APIs have been removed, use
  php_stream_mkdir() instead.