mailparse doesn't support PHP 8.4 anymore (#980)
Error: implicit declaration of function 'php_strtolower'

From https://github.com/php/php-src/blob/php-8.4.0RC1/UPGRADING.INTERNALS:
  The php_strtoupper(), php_string_toupper(), php_strtolower(), and
  php_string_tolower() functions has been removed, use zend_str_toupper(),
  zend_string_toupper(), zend_str_tolower(), and zend_string_tolower()
  respectively instead.